
class Error_Code():
    def __init__(self):
        self._error_code = {'Check_Telnet_Connect' : 'B00WR000003',
                            'Reboot': 'QSFI06', 
                            'Boot_Up' : 'B00OT000002',
                            'Set_Two_Power' : 'Q0ZP00', 
                            'Set_A_Power' : 'Q0ZP00', 
                            'Set_B_Power' : 'Q0ZP00', 
                            'Check_HW_SW_Ver' : 'Q0FO21', 
                            'Check_RTC' : 'QSFT52', 
                            'adc_p0.1_(12v)' : 'QSFI60',
                            'adc_p0.2_(3.3v)' : 'QSFI37',
                            'adc_p0.6_(1.8v)' : 'QSFI32',
                            'adc_p0.7_(0.88v)' : 'B00PO000032',
                            'adc_p1.0_(0.8v)' : 'B00PO000023', 
                            'adc_p1.1_(0.9v_pll)' : 'QSFI27', 
                            'adc_p1.2_(3.3v_stb)' : 'QSFI37', 
                            'adc_p1.5_(0.9v_vdda)' : 'QSFI27', 
                            'adc_p1.6_(1.1v)' : 'B00PO000044', 
                            'fannormal_fan_1_inner_r.p.m' : 'Q0FO02', 
                            'fannormal_fan_2_inner_r.p.m' : 'Q0FO02', 
                            'fannormal_fan_3_inner_r.p.m' : 'Q0FO02', 
                            'fannormal_fan_4_inner_r.p.m' : 'Q0FO02', 
                            'fannormal_fan_5_inner_r.p.m' : 'Q0FO02', 
                            'fannormal_fan_1_outer_r.p.m' : 'Q0FO02',
                            'fannormal_fan_2_outer_r.p.m' : 'Q0FO02', 
                            'fannormal_fan_3_outer_r.p.m' : 'Q0FO02', 
                            'fannormal_fan_4_outer_r.p.m' : 'Q0FO02',
                            'fannormal_fan_5_outer_r.p.m' : 'Q0FO02',
                            'fanalert_count' : 'Q0FO02', 
                            'npu_temperature_lm75b_npu_(addr_0x4a)' : 'QSFT2R', 
                            'npu_temperature_lm75b_pcb_(addr_0x48)' : 'QSFT2R',
                            'npu_temperature_lm75b_pcb_(addr_0x49)' : 'QSFT2R',
                            'npu_temperature_lm75b_fanboard_(addr_0x4a)' : 'QSFT2R',
                            'temperaturealert' : 'Q0FO01', 
                            'cpucoretemperature' : 'Q0FO01', 
                            'alertstatuecheck' : 'QSFT28',
                            'Check_HW_Monitor' : 'QSFT28',
                            'fan0%_fan_1_inner_r.p.m' : 'QSFT2C',
                            'fan0%_fan_2_inner_r.p.m' : 'QSFT2D',
                            'fan0%_fan_3_inner_r.p.m' : 'QSFT2E',
                            'fan0%_fan_4_inner_r.p.m' : 'QSFT2F',
                            'fan0%_fan_5_inner_r.p.m' : 'QSFT2G',
                            'fan0%_fan_1_outer_r.p.m' : 'QSFT2H', 
                            'fan0%_fan_2_outer_r.p.m' : 'QSFT2I',
                            'fan0%_fan_3_outer_r.p.m' : 'QSFT2J',
                            'fan0%_fan_4_outer_r.p.m' : 'QSFT2K', 
                            'fan0%_fan_5_outer_r.p.m' : 'QSFT2L',
                            'Check_Fan0_Speed' : 'Q0FO02',
                            'fan100%_fan_1_inner_r.p.m' : 'QSFT1S',
                            'fan100%_fan_2_inner_r.p.m' : 'QSFT1T',
                            'fan100%_fan_3_inner_r.p.m' : 'QSFT1U',
                            'fan100%_fan_4_inner_r.p.m' : 'QSFT1V',
                            'fan100%_fan_5_inner_r.p.m' : 'QSFT1W',
                            'fan100%_fan_1_outer_r.p.m' : 'QSFT1X', 
                            'fan100%_fan_2_outer_r.p.m' : 'QSFT1Y',
                            'fan100%_fan_3_outer_r.p.m' : 'QSFT1Z',
                            'fan100%_fan_4_outer_r.p.m' : 'QSFT2A', 
                            'fan100%_fan_5_outer_r.p.m' : 'QSFT2B',
                            'Check_Fan0_Speed' : 'Q0FO02',
                            'Fan_auto_mode' : 'Q0FO02',
                            'DRAM_Test' : 'QSFF38', 
                            'SSD_Test' : 'QSFF39', 
                            'Module_Signal_Check' : 'QSFC32',
                            'Set_Loopback_3_5W' : 'Set_Loopback_3_5W', 
                            'Traffic_Test' : 'Q0ZL00',
                            'Loopbak_Test' : 'QSFC10',
                            'Set_Green_light' : 'Q0ZG00',
                            'Set_Red_light' : 'Q0ZG00',}

    def __getitem__(self, data):
        if self._error_code.get(data):
            return self._error_code.get(data)
        else:
            return ''
    



